version: "3.2"
services:
    nginx:
        image: nginx:1.19.3-alpine
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx-reverse-proxy.conf:/etc/nginx/nginx.conf
            - ./ssl/:/etc/nginx/ssl/
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql_data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password
    keycloak:
        image: jboss/keycloak:11.0.2
        ports:
            - 8080
        environment:
            - PROXY_ADDRESS_FORWARDING=true
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=MYSQL
            - DB_ADDR=mysql
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=password
        restart: on-failure
        depends_on:
            - mysql
    backendchallenge:
        image: viniciusschulz/backendchallenge:1.0.5
        ports:
            - 8080
        restart: on-failure
volumes:
    mysql_data:
        driver: local