spring:
  application:
    name: backendchallenge
  datasource:
    url: jdbc:h2:file:./data/schulz
    driverClassName: org.h2.Driver
    username: sa
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
caching:
  ttl: 30