DROP TABLE IF EXISTS CACHE;

CREATE TABLE CACHE (
  id int AUTO_INCREMENT  PRIMARY KEY,
  term VARCHAR NOT NULL,
--  instant DATETIME NOT NULL,
  response VARCHAR NULL,
  commit_id VARCHAR NULL
);